src/accounts/urls.py
#!/usr/bin/env python3

from django.urls import path

from .views import signup_view, login_view, logout_view, auth_status_view


urlpatterns = [
    path("signup/", signup_view, name="signup"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("auth_status/", auth_status_view, name="auth_status"),
]

src/hzd/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('aar/', views.YearView.as_view(), name='years'),
    path('aar/<int:pk>/', views.YearEdit.as_view(), name='year'),
    path('booking/', views.BookingView.as_view(), name='bookings'),
    path('booking/<int:pk>/', views.BookingEdit.as_view(), name='booking'),
    path('frivillige/', views.VolunteerView.as_view(), name='frivillige'),
    path('frivillige/<int:pk>/', views.VolunteerEdit.as_view(), name='frivillig'),
    path('sider/', views.PageView.as_view(), name='sider'),
    path('sider/<int:pk>/', views.PageEdit.as_view(), name='side'),
    path('donationer/', views.DonationView.as_view(), name='donations'),
    path('donationer/<int:pk>/', views.DonationEdit.as_view(), name='donation'),
    path('events/', views.EventView.as_view(), name='events'),
    path('events/<int:pk>/', views.EventEdit.as_view(), name='event'),
    path('kunstnere/', views.ArtistView.as_view(), name='artists'),
    path('kunstnere/<int:pk>/', views.ArtistEdit.as_view(), name='artist'),
    path('program/', views.ProgramView.as_view(), name='programs'),
    path('program/<int:pk>/', views.ProgramEdit.as_view(), name='program'),
    path('areas/', views.VolunteerAreaView.as_view(), name='areas'),
    path('areas/<int:pk>/', views.VolunteerAreaEdit.as_view(), name='area'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/nakkefestival/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include(("year.urls", "year"), namespace="year")),
    path("hzd/", include(("hzd.urls", "hzd"), namespace="hzd")),
    path("admin/", admin.site.urls),
    path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),  # new
    path("accounts/", include("django.contrib.auth.urls")),
]

src/accounts/models.py
from django.db import models
from year.models import VolunteerArea
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    phone = models.CharField(max_length=16)
#    user_status = models.ForeignKey(UserStatus, on_delete=models.CASCADE)
    REQUIRED_FIELDS = ["phone", "email"]

class UserStatus(models.Model):
    name = models.CharField(max_length=50)
    area = models.ForeignKey(VolunteerArea, on_delete=models.CASCADE)

src/accounts/forms.py
#!/usr/bin/env python3

from django import forms
from year.models import VolunteerArea

class SignupForm(forms.Form):
    username = forms.CharField(label="Name", max_length=100)
    email = forms.CharField(label="Email", max_length=200)
    phone = forms.CharField(label="Phone Nimber", max_length=16)
    password = forms.CharField(label="Password", min_length=10)
    repeat_password = forms.CharField(label="Repeat Password", min_length=10)
    area = forms.ModelChoiceField(queryset=VolunteerArea.objects.all())

src/accounts/views.py
from django.http import HttpResponse, HttpResponseNotAllowed
from django.template.loader import get_template
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect

from .models import User
from .forms import SignupForm


def signup_view(request):
    if request.method == "GET":
        context = {
            "title": "Sign Up",
            "bg": "om/vedtaegter.jpg",  # TODO: replace image
        }
        template = get_template("accounts/signup.html")
        return HttpResponse(template.render(context, request))

    if request.method != "POST":
        return HttpResponseNotAllowed(["GET", "POST"])

    form = SignupForm(request.POST)
    if not form.is_valid():
        raise BadRequest(form.errors)

    # TODO: prettier error here
    if not form.cleaned_data["repeat_password"] == form.cleaned_data["password"]:
        raise BadRequest("Password and repeat password must match.")

    user = User.objects.create_user(
        username=form.cleaned_data["username"],
        email=form.cleaned_data["email"],
        password=form.cleaned_data["password"],
        phone=form.cleaned_data["phone"],
    )
    login(request, user)

    # TODO: redirect to somewhere sensible
    return HttpResponse("OK")


def login_view(request):
    if request.method == "GET":
        context = {
            "title": "Log In",
            "bg": "om/vedtaegter.jpg",  # TODO: replace image
        }
        template = get_template("accounts/login.html")
        return HttpResponse(template.render(context, request))

    if request.method != "POST":
        return HttpResponseNotAllowed(["GET", "POST"])

    username = request.POST["username"]
    password = request.POST["password"]
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        # TODO Redirect to a success page.
        return redirect("/")
        # return HttpResponse("OK")
    else:
        # TODO Return an 'invalid login' error message.
        raise BadRequest("Invalid credentials")


def logout_view(request):
    logout(request)
    # TODO Redirect to a success page.
    return HttpResponse("OK")


def auth_status_view(request):
    if not request.user.is_authenticated:
        return HttpResponse("Not logged in.")
    return HttpResponse(f"Logged in as {request.user.username}")

src/accounts/templates/accounts/login.html
{% extends "year/layout.html" %}

{% block content %}
  <div class="container mt-5 pt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="text-center">Log Ind</h2>
        <form method="POST">
          <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
          <div class="form-group mb-3">
            <label for="username">Navn</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
          </div>
          <div class="form-group mb-3">
            <label for="password">Kodeord</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
          </div>
          <button type="submit" class="btn btn-primary">Log Ind</button>
          <a href="{% url 'accounts:signup' %}" class="btn btn-secondary">Opret dig</a>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}

src/accounts/templates/accounts/signup.html
{% extends "year/layout.html" %}

{% block content %}
  <div class="container mt-5 pt-5">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <h2 class="text-center">Tilmelding</h2>
        <form method="POST" >
          <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
          <div class="form-group mb-3">
            <label for="area"></label>
            <select class="form-control" id="area" name="area" placeholder="Område">
              <option value="1"></option>
              <option value="2"></option>
              <option value="3"></option>
            </select>
          </div>
          <div class="form-group mb-3">
            <label for="username">Navn</label>
            <input type="text" class="form-control" id="username" name="username" placeholder="Enter username">
          </div>
          <div class="form-group mb-3">
            <label for="email">Email addresse</label>
            <input type="email" class="form-control" id="email" name="email" placeholder="Enter email">
          </div>
          <div class="form-group mb-3">
            <label for="phone">Telefon</label>
            <input type="tel" class="form-control" id="phone" name="phone" placeholder="Enter phone number">
          </div>
          <div class="form-group mb-3">
            <label for="password">Kodeord</label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Password">
          </div>
          <div class="form-group mb-3">
            <label for="repeat_password">Kodeord Igen</label>
            <input type="password" class="form-control" id="repeat_password" name="repeat_password" placeholder="Repeat Password">
          </div>

          <button type="submit" class="btn btn-primary">Opret bruger</button>
          <a href="{% url 'accounts:login' %}" class="btn btn-secondary">Log ind på eksisterende bruger</a>
        </form>
      </div>
    </div>
  </div>
{% endblock content %}