src/hzd/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('aar/', views.YearView.as_view(), name='years'),
    path('aar/<int:pk>/', views.YearEdit.as_view(), name='year'),
    path('booking/', views.BookingView.as_view(), name='bookings'),
    path('booking/<int:pk>/', views.BookingEdit.as_view(), name='booking'),
    path('frivillige/', views.VolunteerView.as_view(), name='frivillige'),
    path('frivillige/<int:pk>/', views.VolunteerEdit.as_view(), name='frivillig'),
    path('sider/', views.PageView.as_view(), name='sider'),
    path('sider/<int:pk>/', views.PageEdit.as_view(), name='side'),
    path('donationer/', views.DonationView.as_view(), name='donations'),
    path('donationer/<int:pk>/', views.DonationEdit.as_view(), name='donation'),
    path('events/', views.EventView.as_view(), name='events'),
    path('events/<int:pk>/', views.EventEdit.as_view(), name='event'),
    path('kunstnere/', views.ArtistView.as_view(), name='artists'),
    path('kunstnere/<int:pk>/', views.ArtistEdit.as_view(), name='artist'),
    path('program/', views.ProgramView.as_view(), name='programs'),
    path('program/<int:pk>/', views.ProgramEdit.as_view(), name='program'),
    path('areas/', views.VolunteerAreaView.as_view(), name='areas'),
    path('areas/<int:pk>/', views.VolunteerAreaEdit.as_view(), name='area'), 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/nakkefestival/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include(("year.urls", "year"), namespace="year")),
    path("hzd/", include(("hzd.urls", "hzd"), namespace="hzd")),
    path("admin/", admin.site.urls),
    path("accounts/", include(("accounts.urls", "accounts"), namespace="accounts")),  # new
    path("accounts/", include("django.contrib.auth.urls")),
]

src/year/urls.py
from django.urls import path

from . import views

app_name = "year"
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('information/praktisk_information', views.Praktisk_informationView.as_view(), name='praktisk_information'),
    path('information/bliv_frivillig', views.Bliv_frivilligView.as_view(), name='bliv_frivillig'),
    path('information/bliv_kunstner', views.Bliv_kunstnerView.as_view(), name='bliv_kunstner'),
    path('information/fallesbus_til_nakke', views.Fallesbus_til_nakkeView.as_view(), name='fællesbus_til_nakke'),
    path('om/om_nakkefestival', views.Om_nakkefestivalView.as_view(), name='om_nakkefestival'),
    path('om/historien', views.HistorienView.as_view(), name='historien'),
    path('om/find_vej', views.Find_vejView.as_view(), name='find_vej'),
    path('om/billeder', views.BillederView.as_view(), name='billeder'),
    path('om/donationer', views.DonationerView.as_view(), name='donationer'),
    path('om/vedtagter', views.VedtagterView.as_view(), name='vedtagter'),
    path('om/presse', views.PresseView.as_view(), name='presse'),
    path('om/kontakt', views.KontaktView.as_view(), name='kontakt'),
    path('musik/kunstnere/<int:year>/', views.KunstnereView.as_view(), name='kunstnere'),
    # path('musik/kunstnere/<int=year>', views., name=''),
    # path('musik/kunstnere/<slug=band>', view., name''),
    path('musik/program/<int:year>/', views.ProgramView.as_view(), name='program'),
    # path('<int:year>?/musik/program', views.ProgramView.as_view(), name='program'),
    path('musik/events/<int:year>/', views.EventsView.as_view(), name='events'),
]

src/hzd/models.py
from django.db import models

# Create your models here.

src/hzd/views.py
from django.views.generic import TemplateView, ListView, DetailView, UpdateView 
# from django.views.generic.edit import UpdateView
from django.shortcuts import redirect, get_object_or_404 
from django.urls import reverse
from . import urls 
from year.models import Year, Page, ArtistApplication, VolunteerApplication, Donation, Event, Artist, Program, VolunteerArea
from .forms import YearForm, PageForm, ArtistApplicationForm, VolunteerApplicationForm, DonationForm, EventForm, ArtistForm, ProgramForm, VolunteerAreaForm


class IndexView(TemplateView):
    template_name = "hzd/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['title'] = Page.objects.get(id=16).title
        context['bg'] = Page.objects.get(id=16).bg_image
        
        return context

class YearView(ListView):
    template_name = "hzd/year/index.html"
    context_object_name = 'years'
    
    def get_queryset(self):
        # Get the sorting parameter from the request
        sort_by = self.request.GET.get('sort', '-year')
        # Sort queryset based on the parameter
        return Year.objects.all().order_by(sort_by)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=33).title
        context['bg'] = Page.objects.get(id=33).bg_image
        return context

class YearEdit(UpdateView):
    template_name = "hzd/year/year.html"
    context_object_name = 'year_edit'
    model = Year
    form_class = YearForm
    success_url = '/hzd/aar/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=34).title
        context['bg'] = Page.objects.get(id=34).bg_image
        return context

class PageView(ListView):
    template_name = "hzd/sider/index.html"
    context_object_name = 'pages'
    
    def get_queryset(self):
        # Get the sorting parameter from the request
        sort_by = self.request.GET.get('sort', '-url')
        # Sort queryset based on the parameter
        return Page.objects.all().order_by(sort_by)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=19).title
        context['bg'] = Page.objects.get(id=19).bg_image
        return context

class PageEdit(UpdateView):
    template_name = "hzd/sider/side.html"
    context_object_name = 'page_edit'
    model = Page
    form_class = PageForm
    success_url = '/hzd/sider/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=20).title
        context['bg'] = Page.objects.get(id=20).bg_image
        return context

class BookingView(ListView):
    template_name = "hzd/booking/index.html"
    context_object_name = 'artist_applications'
    model = ArtistApplication

    def get_queryset(self):
        sort_by = self.request.GET.get('sort', '-time')
        return ArtistApplication.objects.all().order_by(sort_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=17).title
        context['bg'] = Page.objects.get(id=17).bg_image
        return context

class BookingEdit(UpdateView):
    template_name = "hzd/booking/booking.html"
    context_object_name = 'booking_edit'
    model = ArtistApplication
    form_class = ArtistApplicationForm
    success_url = '/hzd/booking/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=22).title
        context['bg'] = Page.objects.get(id=22).bg_image
        return context

class DonationView(ListView):
    template_name = "hzd/donations/index.html"
    context_object_name = 'donations'
    model = Donation
    
    def get_queryset(self):
        sort_by = self.request.GET.get('sort', '-year')
        return Donation.objects.all().order_by(sort_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=29).title
        context['bg'] = Page.objects.get(id=29).bg_image
        context['model'] = DonationForm()
        return context

class DonationEdit(UpdateView):
    template_name = "hzd/donations/donation.html"
    context_object_name = 'donation_edit'
    model = Donation
    form_class = DonationForm
    success_url = '/hzd/donationer/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=30).title
        context['bg'] = Page.objects.get(id=30).bg_image
        return context

class VolunteerView(ListView):
    template_name = "hzd/frivillige/index.html"
    context_object_name = 'volunteer_applications'
    
    def get_queryset(self):
        sort_by = self.request.GET.get('sort', '-time')
        return VolunteerApplication.objects.all().order_by(sort_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=18).title
        context['bg'] = Page.objects.get(id=18).bg_image
        return context

class VolunteerEdit(UpdateView):
    template_name = "hzd/frivillige/frivillig.html"
    context_object_name = 'volunteer_edit'
    model = VolunteerApplication
    form_class = VolunteerApplicationForm
    success_url = '/hzd/frivillige/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=21).title
        context['bg'] = Page.objects.get(id=21).bg_image
        return context

class EventView(ListView):
    template_name = "hzd/events/index.html"
    context_object_name = 'events'
    
    def get_queryset(self):
        sort_by = self.request.GET.get('sort', '-name')
        return Event.objects.all().order_by(sort_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=25).title
        context['bg'] = Page.objects.get(id=25).bg_image
        return context

class EventEdit(UpdateView):
    template_name = "hzd/events/event.html"
    context_object_name = 'event_edit'
    model = Event
    form_class = EventForm
    success_url = '/hzd/events/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=26).title
        context['bg'] = Page.objects.get(id=26).bg_image
        return context

class ArtistView(ListView):
    template_name = "hzd/artists/index.html"
    context_object_name = 'artists'
    
    def get_queryset(self):
        # Setting default sorting order
        sort_field = self.request.GET.get('sort', 'name')
        current_order = self.request.GET.get('order', 'desc')
        # Changing between asc and desc
        if current_order == 'asc':
            sort_by = sort_field
            next_order = 'desc'
        else:
            sort_by = f'-{sort_field}'
            next_order = 'asc'
        
        self.sort_by = sort_field
        self.next_order = next_order
        return Artist.objects.all().order_by(sort_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=27).title
        context['bg'] = Page.objects.get(id=27).bg_image
        return context

class ArtistEdit(UpdateView):
    template_name = "hzd/artists/artist.html"
    context_object_name = 'artist_edit'
    model = Artist
    form_class = ArtistForm
    success_url = '/hzd/kunstnere/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=28).title
        context['bg'] = Page.objects.get(id=28).bg_image
        return context

class ProgramView(ListView):
    template_name = "hzd/program/index.html"
    context_object_name = 'program'
    
    def get_queryset(self):
        # Setting default sorting order
        sort_field = self.request.GET.get('sort', 'start_time')
        current_order = self.request.GET.get('order', 'desc')
        # Changing between asc and desc
        if current_order == 'asc':
            sort_by = sort_field
            next_order = 'desc'
        else:
            sort_by = f'-{sort_field}'
            next_order = 'asc'
        
        self.sort_by = sort_field
        self.next_order = next_order
        return Program.objects.all().order_by(sort_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=31).title
        context['bg'] = Page.objects.get(id=31).bg_image
        context['current_sort'] = self.sort_by
        context['next_order'] = self.next_order
        return context

class ProgramEdit(UpdateView):
    template_name = "hzd/program/program.html"
    context_object_name = 'program_edit'
    model = Program
    form_class = ProgramForm
    success_url = '/hzd/program/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['title'] = Page.objects.get(id=32).title
        context['bg'] = Page.objects.get(id=32).bg_image
        return context

class VolunteerAreaView(ListView):
    template_name = "hzd/areas/index.html"
    context_object_name = 'volunteer_areas'
    
    def get_queryset(self):
        # Setting default sorting order
        sort_field = self.request.GET.get('sort', 'name')
        current_order = self.request.GET.get('order', 'desc')
        # Changing between asc and desc
        if current_order == 'asc':
            sort_by = sort_field
            next_order = 'desc'
        else:

src/year/templates/hzd/sider/index.html
{% extends "year/page.html" %}
{% block page_content %}
<!-- <div class="row"> -->
<!--   <div class="dropdown"> -->
<!--     <button class="btn btn-secondary dropdown-toggle" style="" type="button" id="dropdownSelectButton" data-bs-toggle="dropdown" aria-expanded="false"> -->
<!--      Select year  -->
<!--     </button> -->
<!--     <ul class="dropdown-menu scroller" aria-labelledby="dropdownSelectButton" style="max-height:15rem;overflow-y:scroll;"> -->
<!--       {% for year_obj in every_year %} -->
<!--        <li class="dropdowm-item "> -->
<!--           <a class="dropdown-item d-block" href="{% url 'year:program' year=year_obj.year %}">{{ year_obj.year }}</a> -->
<!--       </li> -->
<!--       {% endfor %} -->
<!--     </ul> -->
<!--   </div> -->
<!-- </div> -->
{% if pages %}
<div class="table-responsive table-container">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <th><a class="btn btn-primary" href="?sort=title"><b>Title</b></a></th>
      <th><a class="btn btn-primary" href="?sort=url">URL</a></th>
      <th><a class="btn btn-primary" href="?sort=year">Year</a></th>
      <th><a class="btn btn-primary" href="?sort=bg_image">Image</a></th>
      <th><a class="btn btn-primary" href="?sort=published">Published</a></th>
      <th></th>
    </thead>
    {% for page in pages %}
      <tbody>
        <td><b>{{ page.title }}</b></td>
        <td>{{ page.url }}</td>
        <td>{{ page.year }}</td>
        <td>{{ page.bg_image }}</td>
        <td>{{ page.published }}</td>
        <td>
          <a href="{% url 'hzd:side' pk=page.pk %}"><i class="bi bi-pencil-square"></i></a>
        </td>
      </tbody>
    {% endfor %}
  </table>
</div>
{% else %}
  <p> there are no pages to be displayed <p>
{% endif %}
{% endblock page_content %}

src/year/templates/hzd/sider/side.html
{% extends "year/page.html" %}

{% block page_content %}
<!-- <div class="row"> -->
<!--   <div class="dropdown"> -->
<!--     <button class="btn btn-secondary dropdown-toggle" style="" type="button" id="dropdownSelectButton" data-bs-toggle="dropdown" aria-expanded="false"> -->
<!--      Select year  -->
<!--     </button> -->
<!--     <ul class="dropdown-menu scroller" aria-labelledby="dropdownSelectButton" style="max-height:15rem;overflow-y:scroll;"> -->
<!--       {% for year_obj in every_year %} -->
<!--        <li class="dropdowm-item "> -->
<!--           <a class="dropdown-item d-block" href="{% url 'year:program' year=year_obj.year %}">{{ year_obj.year }}</a> -->
<!--       </li> -->
<!--       {% endfor %} -->
<!--     </ul> -->
<!--   </div> -->
<!-- </div> -->
<!-- <form action="" method="post"> -->
<!--     {% csrf_token %} -->
<!--     <div class="mb-3"> -->
<!--         <label for="year" class="form-label">Year</label> -->
<!--         <input type="text" class="form-control" id="year" name="year" value="{{ page_edit.year }}" disabled=disabled> -->
<!--     </div> -->
<!--     <div class="mb-3"> -->
<!--         <label for="url" class="form-label">URL</label> -->
<!--         <input type="text" class="form-control" id="url" name="url" value="{{ page_edit.url }}" disabled=disabled> -->
<!--     </div> -->
<!--     <div class="mb-3"> -->
<!--         <label for="title" class="form-label">Title</label> -->
<!--         <input type="text" class="form-control" id="title" name="title" value="{{ page_edit.title }}"> -->
<!--     </div> -->
<!--     <div class="mb-3"> -->
<!--         <label for="bg_image" class="form-label">Image</label> -->
<!--         <input type="text" class="form-control" id="bg_image" name="bg_image" value="{{ page_edit.bg_image }}"> -->
<!--     </div> -->
<!--     <div class="mb-3"> -->
<!--         <label for="short_description" class="form-label">Manchet</label> -->
<!--         <textarea rows="" cols="" class="form-control" id="short_description" name="short_description">{{ page_edit.short_description }}</textarea>  -->
<!--     </div> -->
<!--     <div class="mb-3"> -->
<!--         <label for="long_description" class="form-label">Tekst</label> -->
<!--         <textarea rows="" cols="" class="form-control" id="long_description" name="long_description" style="min-height:150px;">{{ page_edit.long_description }}</textarea> -->
<!--     </div> -->
<!--     <div class="mb-3"> -->
<!--         <label for="published" class="form-label">Published</label> -->
<!--         <input type="checkbox" class="form-check-input" id="published" name="published" {% if page_edit.published %}checked{% endif %}> -->
<!--     </div> -->
<!--     <button type="submit" class="btn btn-primary">Submit</button> -->
<!-- </form> -->


<div styl="background-image: url('{{ bg.image_url }}');">
    <!-- Include the reusable form template -->
    {% include 'form_snippet.html' with form=form method='post' action='' button_label='Opdater' %}
</div>

{% endblock page_content %}